INSERT INTO USER_DETAILS (ID, NAME,BIRTHDATE)
VALUES(10003,  'Pooja' , current_timestamp());
INSERT INTO USER_DETAILS (ID, NAME,BIRTHDATE)
VALUES(10004,  'Priyanshu' , current_timestamp());
INSERT INTO USER_DETAILS (ID, NAME,BIRTHDATE)
VALUES(10005,  'Archit' , current_timestamp());
INSERT INTO POST (ID,DESCRIPTION,USER_ID)
VALUES(1001,  'THIS IS MY FIRST POST' , 10004);
INSERT INTO POST (ID,DESCRIPTION,USER_ID)
VALUES(2001,  'THIS IS MY Second POST' , 10004);
INSERT INTO POST (ID,DESCRIPTION,USER_ID)
VALUES(3001,  'THIS IS MY Third POST' , 10004);